name: flutter_camera_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  gal: ^2.3.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^0.13.3
  # external_path: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true